# Generated by Django 4.1.7 on 2023-03-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("download_num", models.IntegerField()),
                ("download_title", models.TextField(max_length=100)),
                ("download_link", models.TextField(max_length=500)),
                ("download_desc", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_num", models.IntegerField()),
                ("exp_title", models.TextField(max_length=100)),
                ("exp_desc", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="PDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf_num", models.IntegerField()),
                ("pdf_title", models.TextField(max_length=100)),
                ("pdf_link", models.TextField(max_length=500)),
                ("pdf_desc", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_num", models.IntegerField()),
                ("video_title", models.TextField(max_length=100)),
                ("video_link", models.TextField(max_length=500)),
                ("video_desc", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="XML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xml_num", models.IntegerField()),
                ("xml_title", models.TextField(max_length=100)),
                ("xml_link", models.TextField(max_length=500)),
                ("xml_desc", models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="ExpXML",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_xml", models.CharField(max_length=1000)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.experiment",
                    ),
                ),
                (
                    "xml",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.xml"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_video", models.CharField(max_length=1000)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.experiment",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.video"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_pdf", models.CharField(max_length=1000)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.experiment",
                    ),
                ),
                (
                    "pdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.pdf"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_dload", models.TextField(max_length=500)),
                (
                    "download",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.download",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.experiment",
                    ),
                ),
            ],
        ),
    ]
